[package]
name = "rbf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
libc = "0.2"
